name: ci-cd-automation-build
# Triggers
on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
# Variables
env:
  APP_DIRECTORY: app
  INFRASTRUCTURE_DIRECTORY: infrastructure
# Jobs

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20.x]
        steps:
            - name: Checking out source code
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: Setup Node.js ${{matrix.node-version}}
              uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node-version }}
                cache: "npm"
                cache-dependency-path: ${{ env.APP_DIRECTORY }}/package-lock.json
            - name: Installing project dependencies
              run: npm install
              working-directory: ${{ env.APP_DIRECTORY }}
            - name: Building the application
              run: npm run build-app
              working-directory: ${{ env.APP_DIRECTORY }}
            - name: Uploading application and infrastructure artifacts to Github Pipelines
              if: ${{ github.ref_name == 'main' }}
              uses: actions/upload-artifact@v4
              with:
                name: ${{ env.APP_DIRECTORY }}
                include-hidden-files: true
                path: |
                    ${{ env.APP_DIRECTORY }}/.next
                    ${{ env.APP_DIRECTORY }}/next.config.js
                    ${{ env.APP_DIRECTORY }}/public
                    ${{ env.APP_DIRECTORY }}/scripts
                    ${{ env.APP_DIRECTORY }}/package.json
                    ${{ env.APP_DIRECTORY }}/package-lock.json
                    ${{ env.INFRASTRUCTURE_DIRECTORY }}