name: ci-cd-automation-deploy
on:
  workflow_call:
    inputs:
      template_file_path:
        required: true
        description: Path to bicep template to deploy infrastructure.
        type: string
      workload:
        required: true
        description: Name of the workload
        type: string
      environment:
        required: true
        description: Environment to run this workflow
        type: string
      location:
        required: true
        description: Azure location to carry out deployment
        type: string
      instance_count:
        required: true
        description: Two digit instance count for azure resources
        type: string
      artifact-identifier:
        required: true
        description: release tag or workflow run number
        type: string
env:
  RESOURCE_GROUP_NAME: rg-${{ inputs.workload }}-${{ inputs.environment }}-${{ inputs.location }}-${{ inputs.instance_count }}
  APP_NAME: app-fbitn-${{ inputs.workload }}-${{ inputs.environment }}-${{ inputs.location }}-${{ inputs.instance_count }}
  APP_FOLDER: app
  APPLICATION_ARTIFACT_FOLDER: app-artifact
  CANARY_SLOT_NAME: canary
  REPOSITORY_URL: https://github.com/sriramrakshithkolar/ci-cd-automation

jobs:
  deploy:
    runs-on: [self-hosted, X64, Linux]
    strategy:
      matrix:
        node-version: [20.x]
    environment: ${{ inputs.environment }}
    # deployment is triggered when:
    # 1. Automated build is successful
    # 2. Deployment is run manually
    # 3. Deployment is schedule
    if:
      ${{ github.event_name == 'workflow_run' ||
      github.event_name == 'workflow_dispatch' }}
    steps:
      # this a temp action. Need to find a way to do this at setup or teardown in global fashion
      - name: Cleanup files left from previous deploys
        run: rm -rf ./* || true
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      # getting latest built artifacts from main branch, when no build Id is available
      - name: Downloading artifacts by build ID
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build.yml
          run_id: ${{ inputs.artifact-identifier }}
          path: ${{ env.APPLICATION_ARTIFACT_FOLDER }}
      - name: Login to Azure
        uses: azure/login@v2
        with:
            client-id: ${{ vars.CLIENT_ID }}
            tenant-id: ${{ vars.TENANT_ID }}
            subscription-id: ${{ vars.SUBSCRIPTION_ID }}
      - name: Validating Azure infrastructure
        uses: azure/arm-deploy@v2
        with:
          resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}
          template: ${{ env.APPLICATION_ARTIFACT_FOLDER }}/${{inputs.template_file_path }}
          parameters: environment=${{ inputs.environment }} workload=${{ inputs.workload }} deploymentIdentity=${{ vars.CLIENT_ID }}
          deploymentmode: Validate
          scope: resourcegroup
          failOnStdErr: false
      - name: Deploying Azure infrastructure
        uses: azure/arm-deploy@v2
        with:
          resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}
          template: ${{ env.APPLICATION_ARTIFACT_FOLDER }}/${{inputs.template_file_path }}
          parameters: environment=${{ inputs.environment }} workload=${{ inputs.workload }} deploymentIdentity=${{ vars.CLIENT_ID }}
          deploymentmode: Incremental
          scope: resourcegroup
          failOnStdErr: false
      ### Deploying the web application
      - name: Deploying application to Canary slot
        run: az webapp deploy -n ${{ env.APP_NAME }} -g ${{ env.RESOURCE_GROUP_NAME }} --src-path ./${{ env.APPLICATION_ARTIFACT_FOLDER }}/${{env.APP_FOLDER}}.zip --clean true --restart true --type zip --debug --async
      - name: Checking if Canary slot is UP
        run: |
          timeout --foreground -s TERM 300s bash -c \
          'while [[ "$(curl -s -o /dev/null -m 3 -L -w ''%{http_code}'' $URL)" != "200" ]];\
            do echo "Waiting for $URL" && sleep 10;\
           done' $URL
          TIMEOUT_RETURN="$?"
          echo ${TIMEOUT_RETURN}
          if [[ "${TIMEOUT_RETURN}" == 0 ]]; then
            echo "$URL is UP!"
          else
            echo -e "\n[-] $URL - timeout or other error! [$TIMEOUT_RETURN]"
            exit
          fi
        env:
          URL: ${{inputs.slot_url}}
      - name: Swapping slots
        run: az webapp deployment slot swap -s ${{ env.CANARY_SLOT_NAME }} -n ${{ env.APP_NAME }} -g ${{ env.RESOURCE_GROUP_NAME }} --target-slot ${{ inputs.slot_name }}
      - name: Stop Canary slot
        if: ${{ always() }}
        run: az webapp stop --resource-group ${{ env.RESOURCE_GROUP_NAME }} --name ${{ env.APP_NAME }} --slot ${{env.CANARY_SLOT_NAME}}